from __future__ import annotations

import argparse


def parse_args():
    parser = argparse.ArgumentParser(description="Create a FiftyOne dataset from a video directory.")
    parser.add_argument("--fo-dataset-name", default="re_id", help="Name of the dataset")
    parser.add_argument("--dataset-dir", required=True, help="Path to the videos directory")
    parser.add_argument("--yolo-weights", default="yolo26m.pt", help="Detector weights to load via Ultralytics")
    parser.add_argument("--show", action="store_true", help="Show live video visualization during processing")
    parser.add_argument("--overwrite-loading", action="store_true", help="reload fo dataset")
    parser.add_argument("--overwrite-algo", action="store_true", help="recompute embedding")
    parser.add_argument("--save-visual-debug", action="store_true", help="Save cropped images of each person for visual debugging")
    parser.add_argument("--visual-debug-dir", default="debug_visual", help="Directory to save debug images")
    parser.add_argument("--sim-key", default="embd_sim", help="Brain key for similarity index")
    parser.add_argument("--viz-key", default="embd_viz", help="Brain key for visualization")
    parser.add_argument("--det-batch-size", type=int, default=8, help="Batch size for YOLO frame inference")
    parser.add_argument("--reid-model-name", default="osnet_ain_x1_0", help="Torchreid model name")
    parser.add_argument("--reid-backbone", default="ensemble", choices=["osnet_ain", "clipreid", "ensemble"], help="ReID feature extractor backend")
    parser.add_argument("--reid-model-path", default="", help="Optional fine-tuned ReID checkpoint path")
    parser.add_argument("--reid-weights", default="", help="Override CLIP ReID checkpoint path")
    parser.add_argument("--tracker-type", default="botsort", choices=["bytetrack", "botsort", "strongsort", "deepocsort"], help="Tracker backend")
    parser.add_argument("--tracker-reid-weights", default="", help="ReID weights for StrongSORT/DeepOCSORT (defaults to BoxMOT osnet_x0_25_msmt17.pt)")
    parser.add_argument("--tracker-half", action="store_true", help="Use half precision for tracker ReID model (CUDA only)")
    parser.add_argument("--disable-sparse-clustering", action="store_true", help="Disable sparse neighbor clustering path")
    parser.add_argument("--sparse-threshold", type=int, default=1000, help="Tracklet count threshold to enable sparse clustering")
    parser.add_argument("--linkage", default="min", choices=["min", "mean", "representative"], help="Tracklet linkage for distance computation")
    parser.add_argument("--min-tracklet-frames", type=int, default=2, help="Minimum frames per tracklet")
    parser.add_argument("--disable-quality-weighting", action="store_true", help="Disable confidence/sharpness weighted representative embeddings")
    parser.add_argument("--quality-alpha", type=float, default=0.75, help="Weight of quality scores in representative aggregation [0,1]")
    parser.add_argument("--disable-temporal-smoothing", action="store_true", help="Disable temporal smoothing of embeddings within each tracklet")
    parser.add_argument("--smoothing-window", type=int, default=5, help="Temporal smoothing window size (odd recommended)")
    parser.add_argument("--temporal-penalty", type=float, default=0.05, help="Soft penalty on temporal-center mismatch across clips")
    parser.add_argument("--temporal-max-gap-sec", type=float, default=None, help="Optional hard max gap (seconds) when absolute clip timestamps are parseable")
    parser.add_argument("--motion-penalty", type=float, default=0.05, help="Soft penalty on motion-profile mismatch")
    parser.add_argument("--disable-postprocess-merge", action="store_true", help="Disable post-clustering singleton merge pass")
    parser.add_argument("--postprocess-merge-epsilon", type=float, default=None, help="Distance threshold for post-clustering merges")
    parser.add_argument("--use-rerank", action="store_true", help="Use k-reciprocal re-ranking on representative embeddings")
    parser.add_argument("--cooccurrence-constraint", action="store_true", help="Allow same-clip merges only when tracklets do not overlap")
    parser.set_defaults(use_new_clustering=True)
    parser.add_argument("--use-new-clustering", dest="use_new_clustering", action="store_true", help="Use the HDBSCAN multi-prototype clustering pipeline")
    parser.add_argument("--legacy-clustering", dest="use_new_clustering", action="store_false", help="Use the legacy catalogue_simple clustering pipeline")
    parser.add_argument("--pose-filter", action="store_true", help="Enable MediaPipe pose filtering for V2 keyframe selection")
    parser.add_argument("--scene-backend", default="gemini", choices=["gemini", "videomae", "internvideo"], help="Scene classification backend")
    parser.add_argument("--visualizer", default="fiftyone", choices=["none", "fiftyone", "rerun", "both"], help="Post-run visualization backend")
    parser.add_argument("--rerun-spawn", action="store_true", help="Spawn a Rerun viewer after export")
    parser.add_argument("--rerun-save", default="", help="Optional path to save a Rerun .rrd recording")
    parser.add_argument("--rerun-sample-every", type=int, default=1, help="Sample every Nth frame when exporting frames to Rerun")
    parser.add_argument("--rerun-max-frames-per-clip", type=int, default=None, help="Optional cap on exported frame images per clip")
    parser.add_argument("--finetune-reid", action="store_true", help="Run a self-bootstrap CLIP fine-tune pass before the final clustering pass")
    parser.add_argument("--finetune-min-frames", type=int, default=30, help="Minimum total frames across appearances for pseudo-label fine-tuning")
    parser.add_argument("--finetune-min-prob", type=float, default=0.9, help="Minimum cluster_probability gate for pseudo-label fine-tuning")
    parser.add_argument("--finetune-epochs", type=int, default=5, help="Epoch count for pseudo-label CLIP fine-tuning")
    parser.add_argument("--evaluate", action="store_true", help="Run evaluation against ground_truth.json if available")
    return parser.parse_args()
